[2023-02-10T23:09:18.265+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-01-10T12:55:00+00:00 [queued]>
[2023-02-10T23:09:18.271+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-01-10T12:55:00+00:00 [queued]>
[2023-02-10T23:09:18.271+0200] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-02-10T23:09:18.271+0200] {taskinstance.py:1369} INFO - Starting attempt 1 of 4
[2023-02-10T23:09:18.271+0200] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-02-10T23:09:18.276+0200] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): extract_data_from_api> on 2023-01-10 12:55:00+00:00
[2023-02-10T23:09:18.281+0200] {standard_task_runner.py:52} INFO - Started process 17035 to run task
[2023-02-10T23:09:18.285+0200] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'test_process_sales', 'extract_data_from_api', 'scheduled__2023-01-10T12:55:00+00:00', '--job-id', '988', '--raw', '--subdir', 'DAGS_FOLDER/process_sales/mainS.py', '--cfg-path', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmpe1hdg2yd', '--error-file', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmpmewbmals']
[2023-02-10T23:09:18.286+0200] {standard_task_runner.py:80} INFO - Job 988: Subtask extract_data_from_api
[2023-02-10T23:09:22.802+0200] {process_utils.py:125} INFO - Sending Signals.SIGTERM to group 17035. PIDs of all processes in the group: [17035]
[2023-02-10T23:09:22.803+0200] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 17035
[2023-02-10T23:09:22.806+0200] {process_utils.py:75} INFO - Process psutil.Process(pid=17035, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='23:09:18') (17035) terminated with exit code Negsignal.SIGTERM
[2023-02-10T23:09:24.587+0200] {taskinstance.py:1161} INFO - Dependencies not met for <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-01-10T12:55:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-02-10T23:09:24.592+0200] {taskinstance.py:1161} INFO - Dependencies not met for <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-01-10T12:55:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-02-10T23:09:24.592+0200] {local_task_job.py:101} INFO - Task is not able to be run
